name:                block-monad
version:             0.0.1.0
github:              githubuser/block-monad
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:
# description:
# category:            Web

dependencies:
- base >= 4.7 && < 5
- network > 2.6
- scotty
- MissingH
- aeson
- text
- stm
- distributed-process
- distributed-process-p2p
- network-transport-tcp
- cryptonite
- bytestring
- crdt
- mtl
- binary
- wai
- servant
- servant-server
- servant-client
- time
- http-client
- http-types
- directory
- warp
- containers


library:
  source-dirs: src

executables:
  block-monad-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -Wall
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - block-monad

  chain-example-exe:
    main:                chain_example.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -Wall
    - -rtsopts
    - -Wall
    - -with-rtsopts=-N
    dependencies:
    - block-monad

  flowermap-example-exe:
    main:                flowermap_example.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -Wall
    - -rtsopts
    - -Wall
    - -with-rtsopts=-N
    dependencies:
    - block-monad

  client-exe:
    main:                Main.hs
    source-dirs:         Client
    ghc-options:
    - -threaded
    - -Wall
    - -rtsopts
    - -Wall
    - -with-rtsopts=-N
    dependencies:
    - block-monad

tests:
  block-monad-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -Wall
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - block-monad
